destination: _site/
url: "http://127.0.0.1:4010"
baseurl: "/acre2-pdf"
port: 4010
output: pdf
product: acre2
print_title: Jekyll theme for documentation â€” acre2 product
print_subtitle: version 5.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true
